package model;
// Generated 27/10/2014 12:31:22 AM by Hibernate Tools 4.3.1



/**
 * Promociones generated by hbm2java
 */
public class Promociones  implements java.io.Serializable {


     private int idPromociones;
     private String descripcion;
     private Double descuento;

    public Promociones() {
    }

	
    public Promociones(int idPromociones) {
        this.idPromociones = idPromociones;
    }
    public Promociones(int idPromociones, String descripcion, Double descuento) {
       this.idPromociones = idPromociones;
       this.descripcion = descripcion;
       this.descuento = descuento;
    }
   
    public int getIdPromociones() {
        return this.idPromociones;
    }
    
    public void setIdPromociones(int idPromociones) {
        this.idPromociones = idPromociones;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Double descuento) {
        this.descuento = descuento;
    }




}


