package model;
// Generated 05/11/2014 01:05:10 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TCaja generated by hbm2java
 */
public class TCaja  implements java.io.Serializable {


     private Integer idCaja;
     private TRecepcionista TRecepcionista;
     private Date fecha;
     private Date hora;
     private String descripcion;
     private Double entrada;
     private Double salida;
     private Double saldo;
     private String moneda;

    public TCaja() {
    }

    public TCaja(TRecepcionista TRecepcionista, Date fecha, Date hora, String descripcion, Double entrada, Double salida, Double saldo, String moneda) {
       this.TRecepcionista = TRecepcionista;
       this.fecha = fecha;
       this.hora = hora;
       this.descripcion = descripcion;
       this.entrada = entrada;
       this.salida = salida;
       this.saldo = saldo;
       this.moneda = moneda;
    }
   
    public Integer getIdCaja() {
        return this.idCaja;
    }
    
    public void setIdCaja(Integer idCaja) {
        this.idCaja = idCaja;
    }
    public TRecepcionista getTRecepcionista() {
        return this.TRecepcionista;
    }
    
    public void setTRecepcionista(TRecepcionista TRecepcionista) {
        this.TRecepcionista = TRecepcionista;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(Double entrada) {
        this.entrada = entrada;
    }
    public Double getSalida() {
        return this.salida;
    }
    
    public void setSalida(Double salida) {
        this.salida = salida;
    }
    public Double getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(Double saldo) {
        this.saldo = saldo;
    }
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }




}


