package model;
// Generated 07/06/2015 10:37:49 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TCajalog generated by hbm2java
 */
public class TCajalog  implements java.io.Serializable {


     private Integer idCaja;
     private Date fecha;
     private Date hora;
     private String descripcion;
     private Double entrada;
     private Double salida;
     private Double saldo;
     private Double arqueo;
     private String moneda;
     private String accion;
     private String fechalog;
     private String pc;

    public TCajalog() {
    }

    public TCajalog(Date fecha, Date hora, String descripcion, Double entrada, Double salida, Double saldo, Double arqueo, String moneda, String accion, String fechalog, String pc) {
       this.fecha = fecha;
       this.hora = hora;
       this.descripcion = descripcion;
       this.entrada = entrada;
       this.salida = salida;
       this.saldo = saldo;
       this.arqueo = arqueo;
       this.moneda = moneda;
       this.accion = accion;
       this.fechalog = fechalog;
       this.pc = pc;
    }
   
    public Integer getIdCaja() {
        return this.idCaja;
    }
    
    public void setIdCaja(Integer idCaja) {
        this.idCaja = idCaja;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(Double entrada) {
        this.entrada = entrada;
    }
    public Double getSalida() {
        return this.salida;
    }
    
    public void setSalida(Double salida) {
        this.salida = salida;
    }
    public Double getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(Double saldo) {
        this.saldo = saldo;
    }
    public Double getArqueo() {
        return this.arqueo;
    }
    
    public void setArqueo(Double arqueo) {
        this.arqueo = arqueo;
    }
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }
    public String getAccion() {
        return this.accion;
    }
    
    public void setAccion(String accion) {
        this.accion = accion;
    }
    public String getFechalog() {
        return this.fechalog;
    }
    
    public void setFechalog(String fechalog) {
        this.fechalog = fechalog;
    }
    public String getPc() {
        return this.pc;
    }
    
    public void setPc(String pc) {
        this.pc = pc;
    }




}


