package model;
// Generated 27/10/2014 12:31:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TCliente generated by hbm2java
 */
public class TCliente  implements java.io.Serializable {


     private String idCliente;
     private TPersona TPersona;
     private Set TReservas = new HashSet(0);
     private TJuridica TJuridica;
     private TNatural TNatural;

    public TCliente() {
    }

	
    public TCliente(String idCliente, TPersona TPersona) {
        this.idCliente = idCliente;
        this.TPersona = TPersona;
    }
    public TCliente(String idCliente, TPersona TPersona, Set TReservas, TJuridica TJuridica, TNatural TNatural) {
       this.idCliente = idCliente;
       this.TPersona = TPersona;
       this.TReservas = TReservas;
       this.TJuridica = TJuridica;
       this.TNatural = TNatural;
    }
   
    public String getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }
    public TPersona getTPersona() {
        return this.TPersona;
    }
    
    public void setTPersona(TPersona TPersona) {
        this.TPersona = TPersona;
    }
    public Set getTReservas() {
        return this.TReservas;
    }
    
    public void setTReservas(Set TReservas) {
        this.TReservas = TReservas;
    }
    public TJuridica getTJuridica() {
        return this.TJuridica;
    }
    
    public void setTJuridica(TJuridica TJuridica) {
        this.TJuridica = TJuridica;
    }
    public TNatural getTNatural() {
        return this.TNatural;
    }
    
    public void setTNatural(TNatural TNatural) {
        this.TNatural = TNatural;
    }




}


