package model;
// Generated 13/09/2014 07:59:20 PM by Hibernate Tools 3.6.0



/**
 * THabitaciondetalle generated by hbm2java
 */
public class THabitaciondetalle  implements java.io.Serializable {


     private int idTHabitacionDetalle;
     private THabitacion THabitacion;
     private TTipohabitacion TTipohabitacion;
     private String nroHab;

    public THabitaciondetalle() {
    }

	
    public THabitaciondetalle(int idTHabitacionDetalle, THabitacion THabitacion, TTipohabitacion TTipohabitacion) {
        this.idTHabitacionDetalle = idTHabitacionDetalle;
        this.THabitacion = THabitacion;
        this.TTipohabitacion = TTipohabitacion;
    }
    public THabitaciondetalle(int idTHabitacionDetalle, THabitacion THabitacion, TTipohabitacion TTipohabitacion, String nroHab) {
       this.idTHabitacionDetalle = idTHabitacionDetalle;
       this.THabitacion = THabitacion;
       this.TTipohabitacion = TTipohabitacion;
       this.nroHab = nroHab;
    }
   
    public int getIdTHabitacionDetalle() {
        return this.idTHabitacionDetalle;
    }
    
    public void setIdTHabitacionDetalle(int idTHabitacionDetalle) {
        this.idTHabitacionDetalle = idTHabitacionDetalle;
    }
    public THabitacion getTHabitacion() {
        return this.THabitacion;
    }
    
    public void setTHabitacion(THabitacion THabitacion) {
        this.THabitacion = THabitacion;
    }
    public TTipohabitacion getTTipohabitacion() {
        return this.TTipohabitacion;
    }
    
    public void setTTipohabitacion(TTipohabitacion TTipohabitacion) {
        this.TTipohabitacion = TTipohabitacion;
    }
    public String getNroHab() {
        return this.nroHab;
    }
    
    public void setNroHab(String nroHab) {
        this.nroHab = nroHab;
    }




}


