package model;
// Generated 07/06/2015 10:37:49 PM by Hibernate Tools 4.3.1



/**
 * THabitaciondetalle generated by hbm2java
 */
public class THabitaciondetalle  implements java.io.Serializable {


     private String idTHabitacionDetalle;
     private THabitacion THabitacion;
     private String nroHab;
     private String tipoCama;
     private Integer nroSillas;

    public THabitaciondetalle() {
    }

	
    public THabitaciondetalle(String idTHabitacionDetalle, THabitacion THabitacion) {
        this.idTHabitacionDetalle = idTHabitacionDetalle;
        this.THabitacion = THabitacion;
    }
    public THabitaciondetalle(String idTHabitacionDetalle, THabitacion THabitacion, String nroHab, String tipoCama, Integer nroSillas) {
       this.idTHabitacionDetalle = idTHabitacionDetalle;
       this.THabitacion = THabitacion;
       this.nroHab = nroHab;
       this.tipoCama = tipoCama;
       this.nroSillas = nroSillas;
    }
   
    public String getIdTHabitacionDetalle() {
        return this.idTHabitacionDetalle;
    }
    
    public void setIdTHabitacionDetalle(String idTHabitacionDetalle) {
        this.idTHabitacionDetalle = idTHabitacionDetalle;
    }
    public THabitacion getTHabitacion() {
        return this.THabitacion;
    }
    
    public void setTHabitacion(THabitacion THabitacion) {
        this.THabitacion = THabitacion;
    }
    public String getNroHab() {
        return this.nroHab;
    }
    
    public void setNroHab(String nroHab) {
        this.nroHab = nroHab;
    }
    public String getTipoCama() {
        return this.tipoCama;
    }
    
    public void setTipoCama(String tipoCama) {
        this.tipoCama = tipoCama;
    }
    public Integer getNroSillas() {
        return this.nroSillas;
    }
    
    public void setNroSillas(Integer nroSillas) {
        this.nroSillas = nroSillas;
    }




}


