package model;
// Generated 07/06/2015 10:37:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TIngrediente generated by hbm2java
 */
public class TIngrediente  implements java.io.Serializable {


     private String idtIngrediente;
     private String codIngrediente;
     private String nombre;
     private String cantidad;
     private Double precio;
     private String cantGrasa;
     private String cantCalorias;
     private Set TPlatilloiingredientes = new HashSet(0);

    public TIngrediente() {
    }

	
    public TIngrediente(String idtIngrediente) {
        this.idtIngrediente = idtIngrediente;
    }
    public TIngrediente(String idtIngrediente, String codIngrediente, String nombre, String cantidad, Double precio, String cantGrasa, String cantCalorias, Set TPlatilloiingredientes) {
       this.idtIngrediente = idtIngrediente;
       this.codIngrediente = codIngrediente;
       this.nombre = nombre;
       this.cantidad = cantidad;
       this.precio = precio;
       this.cantGrasa = cantGrasa;
       this.cantCalorias = cantCalorias;
       this.TPlatilloiingredientes = TPlatilloiingredientes;
    }
   
    public String getIdtIngrediente() {
        return this.idtIngrediente;
    }
    
    public void setIdtIngrediente(String idtIngrediente) {
        this.idtIngrediente = idtIngrediente;
    }
    public String getCodIngrediente() {
        return this.codIngrediente;
    }
    
    public void setCodIngrediente(String codIngrediente) {
        this.codIngrediente = codIngrediente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public String getCantGrasa() {
        return this.cantGrasa;
    }
    
    public void setCantGrasa(String cantGrasa) {
        this.cantGrasa = cantGrasa;
    }
    public String getCantCalorias() {
        return this.cantCalorias;
    }
    
    public void setCantCalorias(String cantCalorias) {
        this.cantCalorias = cantCalorias;
    }
    public Set getTPlatilloiingredientes() {
        return this.TPlatilloiingredientes;
    }
    
    public void setTPlatilloiingredientes(Set TPlatilloiingredientes) {
        this.TPlatilloiingredientes = TPlatilloiingredientes;
    }




}


