package model;
// Generated 19/10/2014 11:59:18 PM by Hibernate Tools 4.3.1



/**
 * TNatural generated by hbm2java
 */
public class TNatural  implements java.io.Serializable {


     private String TClienteIdCliente;
     private TCliente TCliente;

    public TNatural() {
    }

    public TNatural(TCliente TCliente) {
       this.TCliente = TCliente;
    }
   
    public String getTClienteIdCliente() {
        return this.TClienteIdCliente;
    }
    
    public void setTClienteIdCliente(String TClienteIdCliente) {
        this.TClienteIdCliente = TClienteIdCliente;
    }
    public TCliente getTCliente() {
        return this.TCliente;
    }
    
    public void setTCliente(TCliente TCliente) {
        this.TCliente = TCliente;
    }




}


