package model;
// Generated 07/06/2015 10:37:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TPedido generated by hbm2java
 */
public class TPedido  implements java.io.Serializable {


     private String idtPedido;
     private TReserva TReserva;
     private Set TPedidodetalles = new HashSet(0);

    public TPedido() {
    }

	
    public TPedido(String idtPedido, TReserva TReserva) {
        this.idtPedido = idtPedido;
        this.TReserva = TReserva;
    }
    public TPedido(String idtPedido, TReserva TReserva, Set TPedidodetalles) {
       this.idtPedido = idtPedido;
       this.TReserva = TReserva;
       this.TPedidodetalles = TPedidodetalles;
    }
   
    public String getIdtPedido() {
        return this.idtPedido;
    }
    
    public void setIdtPedido(String idtPedido) {
        this.idtPedido = idtPedido;
    }
    public TReserva getTReserva() {
        return this.TReserva;
    }
    
    public void setTReserva(TReserva TReserva) {
        this.TReserva = TReserva;
    }
    public Set getTPedidodetalles() {
        return this.TPedidodetalles;
    }
    
    public void setTPedidodetalles(Set TPedidodetalles) {
        this.TPedidodetalles = TPedidodetalles;
    }




}


