package model;
// Generated 07/06/2015 10:37:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TPlatillo generated by hbm2java
 */
public class TPlatillo  implements java.io.Serializable {


     private String idtPlatillo;
     private String codPlatillo;
     private String nombrePlatillo;
     private Double precio;
     private byte[] imgPlatillo;
     private Set TPlatilloiingredientes = new HashSet(0);
     private Set TPedidodetalles = new HashSet(0);

    public TPlatillo() {
    }

	
    public TPlatillo(String idtPlatillo) {
        this.idtPlatillo = idtPlatillo;
    }
    public TPlatillo(String idtPlatillo, String codPlatillo, String nombrePlatillo, Double precio, byte[] imgPlatillo, Set TPlatilloiingredientes, Set TPedidodetalles) {
       this.idtPlatillo = idtPlatillo;
       this.codPlatillo = codPlatillo;
       this.nombrePlatillo = nombrePlatillo;
       this.precio = precio;
       this.imgPlatillo = imgPlatillo;
       this.TPlatilloiingredientes = TPlatilloiingredientes;
       this.TPedidodetalles = TPedidodetalles;
    }
   
    public String getIdtPlatillo() {
        return this.idtPlatillo;
    }
    
    public void setIdtPlatillo(String idtPlatillo) {
        this.idtPlatillo = idtPlatillo;
    }
    public String getCodPlatillo() {
        return this.codPlatillo;
    }
    
    public void setCodPlatillo(String codPlatillo) {
        this.codPlatillo = codPlatillo;
    }
    public String getNombrePlatillo() {
        return this.nombrePlatillo;
    }
    
    public void setNombrePlatillo(String nombrePlatillo) {
        this.nombrePlatillo = nombrePlatillo;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public byte[] getImgPlatillo() {
        return this.imgPlatillo;
    }
    
    public void setImgPlatillo(byte[] imgPlatillo) {
        this.imgPlatillo = imgPlatillo;
    }
    public Set getTPlatilloiingredientes() {
        return this.TPlatilloiingredientes;
    }
    
    public void setTPlatilloiingredientes(Set TPlatilloiingredientes) {
        this.TPlatilloiingredientes = TPlatilloiingredientes;
    }
    public Set getTPedidodetalles() {
        return this.TPedidodetalles;
    }
    
    public void setTPedidodetalles(Set TPedidodetalles) {
        this.TPedidodetalles = TPedidodetalles;
    }




}


