package model;
// Generated 25/09/2014 10:40:56 AM by Hibernate Tools 4.3.1



/**
 * TRecepcionista generated by hbm2java
 */
public class TRecepcionista  implements java.io.Serializable {


     private int idRecepcionista;
     private TPersona TPersona;

    public TRecepcionista() {
    }

    public TRecepcionista(int idRecepcionista, TPersona TPersona) {
       this.idRecepcionista = idRecepcionista;
       this.TPersona = TPersona;
    }
   
    public int getIdRecepcionista() {
        return this.idRecepcionista;
    }
    
    public void setIdRecepcionista(int idRecepcionista) {
        this.idRecepcionista = idRecepcionista;
    }
    public TPersona getTPersona() {
        return this.TPersona;
    }
    
    public void setTPersona(TPersona TPersona) {
        this.TPersona = TPersona;
    }




}


