package model;
// Generated 13/09/2014 07:59:20 PM by Hibernate Tools 3.6.0



/**
 * TReservadetalle generated by hbm2java
 */
public class TReservadetalle  implements java.io.Serializable {


     private Integer idTReservaDetalle;
     private THabitacion THabitacion;
     private TReserva TReserva;

    public TReservadetalle() {
    }

    public TReservadetalle(THabitacion THabitacion, TReserva TReserva) {
       this.THabitacion = THabitacion;
       this.TReserva = TReserva;
    }
   
    public Integer getIdTReservaDetalle() {
        return this.idTReservaDetalle;
    }
    
    public void setIdTReservaDetalle(Integer idTReservaDetalle) {
        this.idTReservaDetalle = idTReservaDetalle;
    }
    public THabitacion getTHabitacion() {
        return this.THabitacion;
    }
    
    public void setTHabitacion(THabitacion THabitacion) {
        this.THabitacion = THabitacion;
    }
    public TReserva getTReserva() {
        return this.TReserva;
    }
    
    public void setTReserva(TReserva TReserva) {
        this.TReserva = TReserva;
    }




}


