package model;
// Generated 17/09/2014 12:29:13 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TReserva generated by hbm2java
 */
public class TReserva  implements java.io.Serializable {


     private int idReserva;
     private TCliente TCliente;
     private String estado;
     private Date fechaRegistro;
     private Date fechaEntrada;
     private Date fechaSalida;
     private String descripcion;
     private Set TReservadetalles = new HashSet(0);

    public TReserva() {
    }

	
    public TReserva(int idReserva, TCliente TCliente, String estado, String descripcion) {
        this.idReserva = idReserva;
        this.TCliente = TCliente;
        this.estado = estado;
        this.descripcion = descripcion;
    }
    public TReserva(int idReserva, TCliente TCliente, String estado, Date fechaRegistro, Date fechaEntrada, Date fechaSalida, String descripcion, Set TReservadetalles) {
       this.idReserva = idReserva;
       this.TCliente = TCliente;
       this.estado = estado;
       this.fechaRegistro = fechaRegistro;
       this.fechaEntrada = fechaEntrada;
       this.fechaSalida = fechaSalida;
       this.descripcion = descripcion;
       this.TReservadetalles = TReservadetalles;
    }
   
    public int getIdReserva() {
        return this.idReserva;
    }
    
    public void setIdReserva(int idReserva) {
        this.idReserva = idReserva;
    }
    public TCliente getTCliente() {
        return this.TCliente;
    }
    
    public void setTCliente(TCliente TCliente) {
        this.TCliente = TCliente;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaEntrada() {
        return this.fechaEntrada;
    }
    
    public void setFechaEntrada(Date fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getTReservadetalles() {
        return this.TReservadetalles;
    }
    
    public void setTReservadetalles(Set TReservadetalles) {
        this.TReservadetalles = TReservadetalles;
    }




}


