package model;
// Generated 17/09/2014 12:29:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TTipohabitacion generated by hbm2java
 */
public class TTipohabitacion  implements java.io.Serializable {


     private int idTTipoHabitacion;
     private String nombre;
     private Set THabitaciondetalles = new HashSet(0);

    public TTipohabitacion() {
    }

	
    public TTipohabitacion(int idTTipoHabitacion) {
        this.idTTipoHabitacion = idTTipoHabitacion;
    }
    public TTipohabitacion(int idTTipoHabitacion, String nombre, Set THabitaciondetalles) {
       this.idTTipoHabitacion = idTTipoHabitacion;
       this.nombre = nombre;
       this.THabitaciondetalles = THabitaciondetalles;
    }
   
    public int getIdTTipoHabitacion() {
        return this.idTTipoHabitacion;
    }
    
    public void setIdTTipoHabitacion(int idTTipoHabitacion) {
        this.idTTipoHabitacion = idTTipoHabitacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getTHabitaciondetalles() {
        return this.THabitaciondetalles;
    }
    
    public void setTHabitaciondetalles(Set THabitaciondetalles) {
        this.THabitaciondetalles = THabitaciondetalles;
    }




}


