package model;
// Generated 07/06/2015 10:37:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TTrabajador generated by hbm2java
 */
public class TTrabajador  implements java.io.Serializable {


     private String idRecepcionista;
     private TPersona TPersona;
     private Double sueldo;
     private Set TCajas = new HashSet(0);

    public TTrabajador() {
    }

	
    public TTrabajador(String idRecepcionista, TPersona TPersona) {
        this.idRecepcionista = idRecepcionista;
        this.TPersona = TPersona;
    }
    public TTrabajador(String idRecepcionista, TPersona TPersona, Double sueldo, Set TCajas) {
       this.idRecepcionista = idRecepcionista;
       this.TPersona = TPersona;
       this.sueldo = sueldo;
       this.TCajas = TCajas;
    }
   
    public String getIdRecepcionista() {
        return this.idRecepcionista;
    }
    
    public void setIdRecepcionista(String idRecepcionista) {
        this.idRecepcionista = idRecepcionista;
    }
    public TPersona getTPersona() {
        return this.TPersona;
    }
    
    public void setTPersona(TPersona TPersona) {
        this.TPersona = TPersona;
    }
    public Double getSueldo() {
        return this.sueldo;
    }
    
    public void setSueldo(Double sueldo) {
        this.sueldo = sueldo;
    }
    public Set getTCajas() {
        return this.TCajas;
    }
    
    public void setTCajas(Set TCajas) {
        this.TCajas = TCajas;
    }




}


