package model;
// Generated 07/06/2015 10:37:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TUbigeo generated by hbm2java
 */
public class TUbigeo  implements java.io.Serializable {


     private int idTUbigeo;
     private String nombre;
     private Set TPersonas = new HashSet(0);

    public TUbigeo() {
    }

	
    public TUbigeo(int idTUbigeo, String nombre) {
        this.idTUbigeo = idTUbigeo;
        this.nombre = nombre;
    }
    public TUbigeo(int idTUbigeo, String nombre, Set TPersonas) {
       this.idTUbigeo = idTUbigeo;
       this.nombre = nombre;
       this.TPersonas = TPersonas;
    }
   
    public int getIdTUbigeo() {
        return this.idTUbigeo;
    }
    
    public void setIdTUbigeo(int idTUbigeo) {
        this.idTUbigeo = idTUbigeo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getTPersonas() {
        return this.TPersonas;
    }
    
    public void setTPersonas(Set TPersonas) {
        this.TPersonas = TPersonas;
    }




}


