package model;
// Generated 25/09/2014 10:40:56 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Promociones generated by hbm2java
 */
public class Promociones  implements java.io.Serializable {


     private int idPromociones;
     private Set TTipohabitacions = new HashSet(0);

    public Promociones() {
    }

	
    public Promociones(int idPromociones) {
        this.idPromociones = idPromociones;
    }
    public Promociones(int idPromociones, Set TTipohabitacions) {
       this.idPromociones = idPromociones;
       this.TTipohabitacions = TTipohabitacions;
    }
   
    public int getIdPromociones() {
        return this.idPromociones;
    }
    
    public void setIdPromociones(int idPromociones) {
        this.idPromociones = idPromociones;
    }
    public Set getTTipohabitacions() {
        return this.TTipohabitacions;
    }
    
    public void setTTipohabitacions(Set TTipohabitacions) {
        this.TTipohabitacions = TTipohabitacions;
    }




}


