package model;
// Generated 13/08/2017 12:19:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TCategoria generated by hbm2java
 */
public class TCategoria  implements java.io.Serializable {


     private Integer idCategoria;
     private String nombreCategoria;
     private String descripcion;
     private Set TProductos = new HashSet(0);

    public TCategoria() {
    }

    public TCategoria(String nombreCategoria, String descripcion, Set TProductos) {
       this.nombreCategoria = nombreCategoria;
       this.descripcion = descripcion;
       this.TProductos = TProductos;
    }
   
    public Integer getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getNombreCategoria() {
        return this.nombreCategoria;
    }
    
    public void setNombreCategoria(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getTProductos() {
        return this.TProductos;
    }
    
    public void setTProductos(Set TProductos) {
        this.TProductos = TProductos;
    }




}


