package model;
// Generated 07/06/2015 10:37:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * THabitacion generated by hbm2java
 */
public class THabitacion  implements java.io.Serializable {


     private String idHabitacion;
     private THotel THotel;
     private TTipohabitacion TTipohabitacion;
     private String nroHabitacion;
     private String descripcion;
     private double precio;
     private Set TReservadetalles = new HashSet(0);
     private Set THabitaciondetalles = new HashSet(0);

    public THabitacion() {
    }

	
    public THabitacion(String idHabitacion, 
                       THotel THotel, 
                       TTipohabitacion TTipohabitacion, 
                       String descripcion, 
                       double precio) {
        this.idHabitacion = idHabitacion;
        this.THotel = THotel;
        this.TTipohabitacion = TTipohabitacion;
        this.descripcion = descripcion;
        this.precio = precio;
    }
    public THabitacion(String idHabitacion, THotel THotel, TTipohabitacion TTipohabitacion, String nroHabitacion, String descripcion, double precio, Set TReservadetalles, Set THabitaciondetalles) {
       this.idHabitacion = idHabitacion;
       this.THotel = THotel;
       this.TTipohabitacion = TTipohabitacion;
       this.nroHabitacion = nroHabitacion;
       this.descripcion = descripcion;
       this.precio = precio;
       this.TReservadetalles = TReservadetalles;
       this.THabitaciondetalles = THabitaciondetalles;
    }
   
    public String getIdHabitacion() {
        return this.idHabitacion;
    }
    
    public void setIdHabitacion(String idHabitacion) {
        this.idHabitacion = idHabitacion;
    }
    public THotel getTHotel() {
        return this.THotel;
    }
    
    public void setTHotel(THotel THotel) {
        this.THotel = THotel;
    }
    public TTipohabitacion getTTipohabitacion() {
        return this.TTipohabitacion;
    }
    
    public void setTTipohabitacion(TTipohabitacion TTipohabitacion) {
        this.TTipohabitacion = TTipohabitacion;
    }
    public String getNroHabitacion() {
        return this.nroHabitacion;
    }
    
    public void setNroHabitacion(String nroHabitacion) {
        this.nroHabitacion = nroHabitacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public Set getTReservadetalles() {
        return this.TReservadetalles;
    }
    
    public void setTReservadetalles(Set TReservadetalles) {
        this.TReservadetalles = TReservadetalles;
    }
    public Set getTHabitaciondetalles() {
        return this.THabitaciondetalles;
    }
    
    public void setTHabitaciondetalles(Set THabitaciondetalles) {
        this.THabitaciondetalles = THabitaciondetalles;
    }




}


