package model;
// Generated 13/09/2014 07:59:20 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TPerfil generated by hbm2java
 */
public class TPerfil  implements java.io.Serializable {


     private int idPerfil;
     private String nombrePrf;
     private String descripPrf;
     private String estado;
     private int accesoHotelIdAccesoHotel;
     private Set TUsuarios = new HashSet(0);

    public TPerfil() {
    }

	
    public TPerfil(int idPerfil, String nombrePrf, String descripPrf, String estado, int accesoHotelIdAccesoHotel) {
        this.idPerfil = idPerfil;
        this.nombrePrf = nombrePrf;
        this.descripPrf = descripPrf;
        this.estado = estado;
        this.accesoHotelIdAccesoHotel = accesoHotelIdAccesoHotel;
    }
    public TPerfil(int idPerfil, String nombrePrf, String descripPrf, String estado, int accesoHotelIdAccesoHotel, Set TUsuarios) {
       this.idPerfil = idPerfil;
       this.nombrePrf = nombrePrf;
       this.descripPrf = descripPrf;
       this.estado = estado;
       this.accesoHotelIdAccesoHotel = accesoHotelIdAccesoHotel;
       this.TUsuarios = TUsuarios;
    }
   
    public int getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(int idPerfil) {
        this.idPerfil = idPerfil;
    }
    public String getNombrePrf() {
        return this.nombrePrf;
    }
    
    public void setNombrePrf(String nombrePrf) {
        this.nombrePrf = nombrePrf;
    }
    public String getDescripPrf() {
        return this.descripPrf;
    }
    
    public void setDescripPrf(String descripPrf) {
        this.descripPrf = descripPrf;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public int getAccesoHotelIdAccesoHotel() {
        return this.accesoHotelIdAccesoHotel;
    }
    
    public void setAccesoHotelIdAccesoHotel(int accesoHotelIdAccesoHotel) {
        this.accesoHotelIdAccesoHotel = accesoHotelIdAccesoHotel;
    }
    public Set getTUsuarios() {
        return this.TUsuarios;
    }
    
    public void setTUsuarios(Set TUsuarios) {
        this.TUsuarios = TUsuarios;
    }




}


