package model;
// Generated 07/06/2015 10:37:49 PM by Hibernate Tools 4.3.1



/**
 * TPlatilloiingrediente generated by hbm2java
 */
public class TPlatilloiingrediente  implements java.io.Serializable {


     private Integer idtPlatilloIingrediente;
     private TIngrediente TIngrediente;
     private TPlatillo TPlatillo;

    public TPlatilloiingrediente() {
    }

    public TPlatilloiingrediente(TIngrediente TIngrediente, TPlatillo TPlatillo) {
       this.TIngrediente = TIngrediente;
       this.TPlatillo = TPlatillo;
    }
   
    public Integer getIdtPlatilloIingrediente() {
        return this.idtPlatilloIingrediente;
    }
    
    public void setIdtPlatilloIingrediente(Integer idtPlatilloIingrediente) {
        this.idtPlatilloIingrediente = idtPlatilloIingrediente;
    }
    public TIngrediente getTIngrediente() {
        return this.TIngrediente;
    }
    
    public void setTIngrediente(TIngrediente TIngrediente) {
        this.TIngrediente = TIngrediente;
    }
    public TPlatillo getTPlatillo() {
        return this.TPlatillo;
    }
    
    public void setTPlatillo(TPlatillo TPlatillo) {
        this.TPlatillo = TPlatillo;
    }




}


