package model;
// Generated 13/08/2017 12:19:32 PM by Hibernate Tools 4.3.1



/**
 * TProducto generated by hbm2java
 */
public class TProducto  implements java.io.Serializable {


     private Integer idProducto;
     private TCategoria TCategoria;
     private String nombreProducto;
     private Double precioUnitario;
     private Integer stock;
     private String imagen;

    public TProducto() {
    }

    public TProducto(TCategoria TCategoria, String nombreProducto, Double precioUnitario, Integer stock, String imagen) {
       this.TCategoria = TCategoria;
       this.nombreProducto = nombreProducto;
       this.precioUnitario = precioUnitario;
       this.stock = stock;
       this.imagen = imagen;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public TCategoria getTCategoria() {
        return this.TCategoria;
    }
    
    public void setTCategoria(TCategoria TCategoria) {
        this.TCategoria = TCategoria;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public Double getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(Double precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * @return the imagen
     */
    public String getImagen() {
        return imagen;
    }

    /**
     * @param imagen the imagen to set
     */
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }



    


}


