package model;
// Generated 19/10/2014 11:59:18 PM by Hibernate Tools 4.3.1



/**
 * TRecepcionista generated by hbm2java
 */
public class TRecepcionista  implements java.io.Serializable {


     private String idRecepcionista;
     private TPersona TPersona;

    public TRecepcionista() {
    }

    public TRecepcionista(String idRecepcionista, TPersona TPersona) {
       this.idRecepcionista = idRecepcionista;
       this.TPersona = TPersona;
    }
   
    public String getIdRecepcionista() {
        return this.idRecepcionista;
    }
    
    public void setIdRecepcionista(String idRecepcionista) {
        this.idRecepcionista = idRecepcionista;
    }
    public TPersona getTPersona() {
        return this.TPersona;
    }
    
    public void setTPersona(TPersona TPersona) {
        this.TPersona = TPersona;
    }




}


