package model;
// Generated 14/08/2017 12:04:36 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TResxprod generated by hbm2java
 */
public class TResxprod  implements java.io.Serializable {


     private Integer idResxProd;
     private TProducto TProducto;
     private TReserva TReserva;
     private Integer cantidad;
     private Double total;
     private Double montoCancelado;
     private Double montoRestante;
     private String estado;
     private Date fecha;

    public TResxprod() {
    }

	
    public TResxprod(TProducto TProducto, TReserva TReserva) {
        this.TProducto = TProducto;
        this.TReserva = TReserva;
    }
    public TResxprod(TProducto TProducto, TReserva TReserva, Integer cantidad, Double total, Double montoCancelado, Double montoRestante, String estado, Date fecha) {
       this.TProducto = TProducto;
       this.TReserva = TReserva;
       this.cantidad = cantidad;
       this.total = total;
       this.montoCancelado = montoCancelado;
       this.montoRestante = montoRestante;
       this.estado = estado;
       this.fecha = fecha;
    }
   
    public Integer getIdResxProd() {
        return this.idResxProd;
    }
    
    public void setIdResxProd(Integer idResxProd) {
        this.idResxProd = idResxProd;
    }
    public TProducto getTProducto() {
        return this.TProducto;
    }
    
    public void setTProducto(TProducto TProducto) {
        this.TProducto = TProducto;
    }
    public TReserva getTReserva() {
        return this.TReserva;
    }
    
    public void setTReserva(TReserva TReserva) {
        this.TReserva = TReserva;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Double getMontoCancelado() {
        return this.montoCancelado;
    }
    
    public void setMontoCancelado(Double montoCancelado) {
        this.montoCancelado = montoCancelado;
    }
    public Double getMontoRestante() {
        return this.montoRestante;
    }
    
    public void setMontoRestante(Double montoRestante) {
        this.montoRestante = montoRestante;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


