package model;
// Generated 07/06/2015 10:37:49 PM by Hibernate Tools 4.3.1



/**
 * TReservadetalle generated by hbm2java
 */
public class TReservadetalle  implements java.io.Serializable {


     private Integer idTReservaDetalle;
     private THabitacion THabitacion;
     private TReserva TReserva;
     private Double costo;

    public TReservadetalle() {
    }

	
    public TReservadetalle(THabitacion THabitacion, TReserva TReserva) {
        this.THabitacion = THabitacion;
        this.TReserva = TReserva;
    }
    public TReservadetalle(THabitacion THabitacion, TReserva TReserva, Double costo) {
       this.THabitacion = THabitacion;
       this.TReserva = TReserva;
       this.costo = costo;
    }
   
    public Integer getIdTReservaDetalle() {
        return this.idTReservaDetalle;
    }
    
    public void setIdTReservaDetalle(Integer idTReservaDetalle) {
        this.idTReservaDetalle = idTReservaDetalle;
    }
    public THabitacion getTHabitacion() {
        return this.THabitacion;
    }
    
    public void setTHabitacion(THabitacion THabitacion) {
        this.THabitacion = THabitacion;
    }
    public TReserva getTReserva() {
        return this.TReserva;
    }
    
    public void setTReserva(TReserva TReserva) {
        this.TReserva = TReserva;
    }
    public Double getCosto() {
        return this.costo;
    }
    
    public void setCosto(Double costo) {
        this.costo = costo;
    }




}


